### ISSUE TITLE
Program's EXEC SQL statements contained in copybooks so testing program for isSQL returns false

### ISSUE THREAD

**Issue by drbruce-git** [IBM/dbb-zappbuild#108]
However since the scanner will make any copybooks with EXEC SQL statements in them as isSQL = true, we should be able to scan the resolved dependency logical files during dependency resolution and update the program's in memory logical file with the correct flag setting.

**Comment by dennis-behm** [comment]
Using the new option with the _SearchPathImpactFinder_ and _SearchPathDependencyResolver_ using the `useSearchConfiguration`, the file flags can be set based on included / nested dependencies.

See configuration `resolveSubsystems` within `application-conf` sample:

https://github.com/IBM/dbb-zappbuild/blob/f078a6668497c466ad889a73808d8d0fbe1b34ce/samples/application-conf/application.properties#L131-L137
