### ISSUE TITLE
zAppBuild/build-conf/README.md: Strange characters in the file

### ISSUE THREAD

**Issue by jbyibm** [IBM/dbb-zappbuild#121]
This can lead into a clone issue.
See capture:
![image](https://user-images.githubusercontent.com/60784175/123922427-4fa62400-d988-11eb-834b-639bb953d4e0.png)

**Comment by dennis-behm** [comment]
Thanks for reporting the issue, @jbyibm. It should now be fixed.

**Comment by dennis-behm** [comment]
Closed per #124
