### ISSUE TITLE
Automation of fileranks in static link scenario

### ISSUE THREAD

**Issue by drbruce-git** [IBM/dbb-zappbuild#13]
This issue is for ordering he processing of programs, when programs are statically linked.

In this case we need to process the sub-modules first, so the recompiled submodule is included into the main-executable.

If we have 2 COBOL programs: MAINPGM1 which statically calls SUBPROG1. If we change SUBPROG1 and performs a impactBuild, we will identify that we have an dependency in the output collection to MAINPGM1, so both will be processed. However due to the alphabetic order, MAINPGM1 will be processed first, and therefore include the old version of SUBPROG1.

The current implementation of zAppBuild on allows us to do fileRanking, and we therefore need to identify all the submodules to get them to process first.

In many cases this is not defined specifically in existing Library Managers. In some cases the user relies on the validation that happens during promotion in the Library Manager, which can ensure that all executable with SUBPROG1 contains the latest version of SUBPROG1, and the user can then manipulate the order of the compiles.

**Comment by dangeville-n** [comment]
Closing as we move it to a design issue tracked in a different place.
