### ISSUE TITLE
To implement jenkins ci pipeline if buildlist is zero

### ISSUE THREAD

**Issue by yamuna-tandra** [IBM/dbb-zappbuild#142]
Hi team, if i run build in jenkins ci pipeline in impact build mode with out doing any action then the build list is zero and nothing is there to compile and package is not generating.i would like to know is there any way to create any empty tar file to generate the package if build list is zero. So further stages in jenkins pipeline might not get fail.

**Comment by dennis-behm** [comment]
Hi @yamuna-tandra, what I understand from your request is, that you would like to skip some steps in your pipeline when the file list is empty, while there is no need to perform a packaging in this case.

This logic needs to be implemented in your Jenkinsfile. See the below link to a sample Jenkinsfile which validates the number of files where are processed.

https://github.com/IBM/dbb-pipeline/blob/master/cics-genapp/Jenkinsfile#L162-L164

In the subsequent steps, conditional logic makes sure that the steps are only executed, when files got processed.

**Comment by dennis-behm** [comment]
@yamuna-tandra is this request resolved?
