### ISSUE TITLE
Renamed Files List not writing in the Output logs folder

### ISSUE THREAD

**Issue by kiran-esh2612** [IBM/dbb-zappbuild#153]
Hi Team,

I found renamed list got gathered logically but not writing the renamedFileList.txt into the output log folder.
Any plan to implement this next releases. Please take this up as we are in need to get this list and process them in our deployment process.

Thanks :-)

**Comment by dennis-behm** [comment]
Hi @kiran-esh2612 ,

zAppBuild manages the changed, renamed and deleted files. Indeed, deleted files are currently written to the output dir.

Do you plan on any post-build processing for renamed files ? If so, can you please elaborate on the use case a bit?

**Comment by kiran-esh2612** [comment]
We need list of renames files so that during deployment we can remove those components from our loadlibs, source libs etc and will avoid referring of renamed code in any case and will maintain our libs with out any unnecessary components.

**Comment by dennis-behm** [comment]
Hi Kiran, 

There is a larger enhancement that we are planning to contribute, which is about documenting the deletions (and now also renaming) as DBB Build Report records, to be able to process the deletions through UCD. Basically, these are deleted source files with their assumed generated outputs.

You can have a preview here. 
https://github.com/dennis-behm/dbb-zappbuild/compare/main...dennis-behm:documentDeletions

Would that address your scenario?

**Comment by kiran-esh2612** [comment]
I'm glad to hear about the larger enhancement.
Meanwhile we have taken care of writing renameFileList.txt into output log folder.
Thanks :-)
