### ISSUE TITLE
Deploy asset that don't require any transformation

### ISSUE THREAD

**Issue by marvin42-fr** [IBM/dbb-zappbuild#155]
Hello,

Is it possible to deploy asset that do not require a transformation ?
For exemple we need to deploy "JCL" included in the project in a targeted HLQ.
We want to include thoses JCL in the shiplist to use with Urban Codedeploy like LOAD or DBRM.

Regards,
Eric Bartolone.

**Comment by dennis-behm** [comment]
Hi Eric, can you please browse the PR, which I linked to this request? I struggle to find a good name for the new language script ... If you have a better idea than `nonBuildable`, please let me know.

**Comment by marvin42-fr** [comment]
Hi Dennis,
Thanks i browse this new language script that seems to be what i'm searching for.
Does a name like 'statics' like is it for static ressources on web application?

Regards,
Eric Bartolone.

**Comment by dennis-behm** [comment]
Hi Eric, I have merged the functionality via #156 to `develop` and plan to create a new release next week. Please let us know all your feedback.

**Comment by marvin42-fr** [comment]
Hi Dennis, 
It's working exactly as expected for the files i need to ass to the package.
We also need to do others personilazed task on thoses files before adding them to the package (like replacing value, or create an englobing JCL) so this will help me implement it.

Thanks a lot.
Regards,
Eric Bartolone.

**Comment by dennis-behm** [comment]
Hi Eric, I am closing the Issue, while it got released to zAppBuild via #160
