### ISSUE TITLE
Create logical files for text files without scanning source files

### ISSUE THREAD

**Issue by drbruce-git** [IBM/dbb-zappbuild#200]
There are scenarios when text files need to be built i.e. copied from the local git repository to datasets during a build.  However the DBB Dependency Scanner should not scan these files as it often does not understand the syntax and either is a waste of process time or in some cases causes exceptions to be thrown or poor performance.

Instead zAppBuild should just create a default logical file to be used during impact analysis.

**Comment by drbruce-git** [comment]
One solution would be:
1) Create a new build property.  It can go in the text.properties file:
```
#
# list of text file types to create logical files for without scanning source
textFileList=**/*.pkg,**/*.ctl, **/*.pln
```

2) In ImpactUtilities.groovy at https://github.com/IBM/dbb-zappbuild/blob/main/utilities/ImpactUtilities.groovy#L805-L807

replace
```
            def scanner = buildUtils.getScanner(file)
            try {
               def logicalFile = scanner.scan(file, props.workspace)
```
with
```
            try {
                LogicalFile logicalFile = null
                // create a default logical file for text source file
                List<PathMatcher> textFileMatchers = createPathMatcherPattern(props.textFileList)
                if (matches(file, textFileMatchers)) {
                    if (props.verbose) println "*** Creating default TEXT logical file"
                    String lname = CopyToPDS.createMemberName(file)
                    logicalFile = new LogicalFile(lname, file, "TEXT", false, false, false)
                }
                // else scan the source file
                else {       
                    def scanner = buildUtils.getScanner(file)
                    logicalFile = scanner.scan(file, props.workspace)
                }
```

**Comment by dennis-behm** [comment]
Delivered in [zAppBuild Release 3.3.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.3.0)
