### ISSUE TITLE
writing build reports takes long time

### ISSUE THREAD

**Issue by nk2164** [IBM/dbb-zappbuild#21]
I am trying to run the zappbuild through command line . The program build itself runs pretty quick , but i think it take a long time to write the actual build report. I see a long pause after that below line and then it completes OK. 

** Writing build report data to /u/xx/BuildReport ***

We just use the default templates that came with dbb. Is this expected ? Not sure if i am missing anything . Is there any recommendation ?

**Comment by dennis-behm** [comment]
Hi nk2164,
I never saw this step taking a long time. Can you confirm that when you println the timestamp before and after of that section - https://github.com/IBM/dbb-zappbuild/blob/development/build.groovy#L436? What type of build do you perform (impact, user, full), how many files are included?

More a guess ... does it wait for the ZFS to be extended? Is your file system full? Does it change, when you use a different directory on a different FS?

**Comment by nk2164** [comment]
I am doing a user build with just 1 file. I give a files.txt as input . I tried giving --verbose option and then it paused after this. So you are right , its not that step. 

> ** Writing build report data to /x/xxxx/build/out/BuildReport.json
** Writing build report to /x/xxxx/build/out/BuildReport.html
** Updating build result BuildGroup:-xxxx-xxxx BuildLabel:build.20200604.023824.038
*** Obtaining hash for directory /u/xxxx/xxxx/xxxx
** Setting property :githash:xxxx : xxxx

and then i see this 

> ** Build ended at Thu Jun 04 03:49:18 GMT 2020
** Build State : CLEAN
** Total files processed : 1
** Total build time  : 1 minutes, 25.173 seconds

In b/w that , the only thing i see is `buildResult.save()` , so it is happening on save. I will try on some other system tomorrow and  let you know.

But i did a `df -k` for my drive and see this . So it looks like i have enough space.

> Mounted on     Filesystem             Avail/Total    Files      Status
/xx/xxxx        (xx.HFS.xxxx)       107055/151200  4294967012 Available

**Comment by dennis-behm** [comment]
Where you able to resolve this issue? If so, would you mind to close it? Thank you.

**Comment by nk2164** [comment]
I got pulled into some other work and could spend time researching this .But i will close it for now. Will open another one once i have had some time to do more research and get additional details . Thank you @dennis-behm .
