### ISSUE TITLE
REXX.groovy uses incorrect property key for compileErrorFeedbackXmlOptions

### ISSUE THREAD

**Issue by sdearth** [IBM/dbb-zappbuild#223]
REXX.groovy method `createCompileCommand` references the value of BuildProperty `cobol_compileErrorFeedbackXmlOptions` when adding DD for `SYSXMLSD`. I suspect that this should be a REXX specific property.

**Comment by dennis-behm** [comment]
Delivered with [zApppBuild Release 2.5.0](https://github.com/IBM/dbb-zappbuild/releases/tag/2.5.0)
