### ISSUE TITLE
Missing a COBOL program on the provided Mortgage sample.

### ISSUE THREAD

**Issue by RegiBrazil** [IBM/dbb-zappbuild#27]
A COBOL program [EPSCSMRT.cbl](https://github.com/RegiBrazil/dbb-zappbuild-1/blob/sandbox2/samples/MortgageApplication/cobol/EPSCSMRT.cbl) is missing.  This cause a bad mortgage calculation when running the transaction **EPSP.**

This missing program also must be compiled with CICS option since is invoked via CICS LINK (like it is now epsmlist.cbl), 
Once you add the missing program also need to update the [file.properties](https://github.com/RegiBrazil/dbb-zappbuild-1/blob/sandbox2/samples/MortgageApplication/application-conf/file.properties)  :
```
# epsmlist needs to compile as CICS but does not have EXEC CICS statements   
# so is not automatically flagged as CICS by dependency scanner   
# added by Regi - July 27,2020 - EPSCSMRT also must be compiled with CICS option as added below 

 isCICS = true :: **/cobol/epsmlist.cbl, **/cobol/EPSCSMRT.cbl**`
````

If not compiling with CICS the transaction will have an ASRA abend.
Once this is done the application now works as it should be.
More details at #dbb-git-zsystems slack.

**Comment by dennis-behm** [comment]
Resolved via #32

**Comment by RegiBrazil** [comment]
> 
> 
> Resolved via #32

@dennis-behm  the statements below are not on file.properties any longer..  How the framework identify if the program needs to be compiled with CICS option?

Parsing for EXEC CICS on the code is not enough..  Example the programs epsmlist.cbland and EPSCSMRT.cbl need to be compiled with option CICS even they do not have the statements EXEC CICS.
On previous file.properties we had the below (that is not there any longer):
```
```
# epsmlist needs to compile as CICS but does not have EXEC CICS statements   
# so is not automatically flagged as CICS by dependency scanner   
# added by Regi - July 27,2020 - EPSCSMRT also must be compiled with CICS option as added below 

 isCICS = true :: **/cobol/epsmlist.cbl, **/cobol/EPSCSMRT.cbl**`
``` 
```

**Comment by dennis-behm** [comment]
Hi Regi, are we looking at the same file.properties?
#32 has added that to file.properties - see https://github.com/IBM/dbb-zappbuild/blob/development/samples/MortgageApplication/application-conf/file.properties#L22

**Comment by RegiBrazil** [comment]
> 
> 
> Hi Regi, are we looking at the same file.properties?
> #32 has added that to file.properties - see https://github.com/IBM/dbb-zappbuild/blob/development/samples/MortgageApplication/application-conf/file.properties#L22

Maybe I was looking a wrong file.properties..  Yes, its fine there. thanks.
