### ISSUE TITLE
Documentation of the BuildReport.json file

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb-zappbuild#279]
Hi,

Is there documentation describing the structure and content of the BuildReport.json file, and other related files?

Thanks.

**Comment by dennis-behm** [comment]
@FALLAI-Denis , please have a look to the IBM Docs centre for DBB:
https://www.ibm.com/docs/en/dbb/2.0.0?topic=apis-build-report

The JavaDoc for the reports:
https://www.ibm.com/docs/api/v1/content/SS6T76_2.0.0/javadoc/com/ibm/dbb/build/report/records/Record.html

Also the Self-paced training has a talks about the Buildreport 
https://ibm.github.io/mainframe-downloads/Training/dbb-self-paced-learning.html
