### ISSUE TITLE
COBOL compiler does not require SYSUT16 and SYSUT17.

### ISSUE THREAD

**Issue by flpet-ibm** [IBM/dbb-zappbuild#322]
cobol.groovy is allocating SYSUT01 to SYSUT17. However the compiler is only using SYSUT01 to SYSUT15. 

https://www.ibm.com/docs/en/cobol-zos/6.4?topic=output-data-sets-used-by-compiler-under-zos

The language script should be changed to avoid the unnecessary allocations.

**Comment by wfezzani** [comment]
My system has a storage group which seems to prevent the allocation of temporary data.
So I have made a test to build a Cobol program with values 17 and 16 in the Cobol.groovy script, it didn't work.
But test OK with value 15:
(1..15).toList().each { num ->
		compile.dd(new DDStatement().name("SYSUT$num").options(props.cobol_tempOptions))
	}

**Comment by dennis-behm** [comment]
This has been delivered with [zAppBuild Release 3.6.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.6.0)
