### ISSUE TITLE
Question: how to specify different DCB specs for transfer.groovy 

### ISSUE THREAD

**Issue by rsjrny** [IBM/dbb-zappbuild#327]
I have a situation where I need to transfer files that are different DCB; lrecl 80 and lrecl 255

copybooks are 80 lrecl
sample members are 255 lrecl

I do not see in the transfer or files properties where I can specify different lrecl values

I may be missing it so your assistance is greatly appreciated.

**Comment by rsjrny** [comment]
I believe issue #251 addresses my concern.

**Comment by dennis-behm** [comment]
@rsjrny I have not yet created the PR for it, but the implementation of the enhancement is [here](https://github.com/IBM/dbb-zappbuild/compare/develop...dennis-behm:dbb-zappbuild:318_uplift_transfer_script?expand=1 ).

I am missing the documentation of it, so no PR (yet).

Does that address your concern?
