### ISSUE TITLE
Enhancement: add ASMAOPT option to the Assembler.groovy and a parm in the Assembler.properties

### ISSUE THREAD

**Issue by rsjrny** [IBM/dbb-zappbuild#329]
We rely in the ASMAOPT DD in our assemblies. I had to modify the Assembler.groovy in this fashion to accomplish my need

```
def asmOPTS = props.getFileProperty('assembler_asmaoptMEM', buildFile) ?: ""
if (asmOPTS)
     assembler.dd(new DDStatement().name("ASMAOPT").dsn("${asmOPTS}").options("shr"))

```
In the Assembler.properties I added: 

`assembler_asmaoptMEM=PPPPVNNN.DLSC.MACLIB(ASMAOPT)`

**Comment by dennis-behm** [comment]
Was delivered via zAppBuild Version 3.2.0 https://github.com/IBM/dbb-zappbuild/pull/354 

However, this external options file should be moved to the central zappbuild configurations to avoid managing build configuration outside of the build framework and repository. 

For instance once building on a different LPAR, the build might fail.
