### ISSUE TITLE
Question - How to build a list of Programs without updating MetadataStore

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb-zappbuild#333]
Hi,

We have a use case where we would like to build a list of items (programs or other types of items), without updating the MetadataStore nor store build results.

That is to say, do a `--userBuild` but on a list of elements and not a single isolated element.

This use case is a priori not explicitly described in the documentation.

Is the "--userBuild aFileList.txt" syntax supported and will provide the expected result?

Reading the code of the `build.groovy` script, `createBuildList` function, it seems to be possible, but would there be other things to consider?

Thanks.

**Comment by dennis-behm** [comment]
Hi Denis,

yes, you can pass a `<buildList>.txt`. Based on the file extension, zAppBuild is going over the list.

`--userBuild` is the only option, which will skip connecting to the metadata store.

Obviously, it will also not create an entry in the build result group for any future impactBuilds.

You might also read : https://github.com/IBM/dbb-zappbuild/wiki/Forcing-files-to-be-built
