### ISSUE TITLE
MFS. groovy

### ISSUE THREAD

**Issue by yamuna-tandra** [IBM/dbb-zappbuild#346]
Hi, 

We have been using ibmdbb  code for one of our application. Where as in MaFS.groovy we are expecting TFORMAT pds to be copy into buildreport. Json which is not handling in existing code. 

Could you please help us to get the requirement. 

mfsPhase2.dd(new DDStatement().name("FORMAT").dsn(props.mfs_tformatPDS).options("shr").output(true).deployType(deployType))
	// mfsPhase2.dd(new DDStatement().name("DUMMY").dsn("${props.PROCLIB}(FMTCPY)").options("shr"))
	mfsPhase2.dd(new DDStatement().name("TASKLIB").dsn(props.SDFSRESL

**Comment by dennis-behm** [comment]
Delivered via [zAppBuild Release 3.5.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.5.0)
