### ISSUE TITLE
CICS definitions are missing for the Mortgage application

### ISSUE THREAD

**Issue by RegiBrazil** [IBM/dbb-zappbuild#35]
If customer wants to try the CICS Mortgage application will need to define the CICS Resources..
It would be nice to add this along with the sample code.

[DEFEPS.txt](https://github.com/IBM/dbb-zappbuild/files/5099464/DEFEPS.txt)

**Comment by dennis-behm** [comment]
Delivered via zAppBuild Release 3.4.0 (#392).
Feedback welcome via #410
