### ISSUE TITLE
Question - capturing SYSPRINT to a permanent PDS member

### ISSUE THREAD

**Issue by rsjrny** [IBM/dbb-zappbuild#356]
We have some post-build processing that relies on the assembler and linkedit listing to be stored in their own PDS members.   

I do not want to change the current store of the complete SYSPRINT in HFS but I also want to capture the SYSPRINT from the assembly step and send it to ${hlq}.asmout(${member}) and capture the SYSPRINT from the linkedit step and send it to ${hlq}.linkout(${member})

It does not look like copytoPDS will allow me to copy a z/os temp file to a z/OS dataset so adding a copytoPDS in each step will not work. If I add a copytoPDS after the copytoHFS in each step I will get the appended listing

I am open to all ideas.

thanks

**Comment by dennis-behm** [comment]
Hi @rsjrny ,

You don't need to consider to upload the sysprint again. You only need to change the current temporary allocations to a "real" dataset.

Here is a sample for this:
https://github.com/IBM/dbb-zappbuild/compare/develop...dennis-behm:dbb-zappbuild:storeListinginDataset?expand=1

**Comment by rsjrny** [comment]
Thanks @dennis-behm,

just what the doctor ordered
