### ISSUE TITLE
Can buildOrder have a default value in build.properties. Can application.properties be optional ?

### ISSUE THREAD

**Issue by drbruce-git** [IBM/dbb-zappbuild#38]
Customer wants to minimize the application specific properties. Looks like buildOrder could be defined in build.properties for everyone.

Some properties are defined in both build.properties and application.properties. buildOrder is only in application.properties, I think it would make sense for it to be in build.properties.

I actually wonder if all properties of application.properties should be in build.properties as well, to provide defaults.

Note that loading application.properties is mandatory in build.groovy. If there are defaults for everything in build.properties, then we could make loading application.properties optional.

**Comment by dirkthielens** [comment]
Working on setup DBB setup we were also thinking which properties we would like to move from application.properties to build.properties because we would like to have default for multiple applications and to be able to maintain them more efficient.

**Comment by dennis-behm** [comment]
See the updates which got delivered via zAppBuild 3.4.0 - https://github.com/IBM/dbb-zappbuild/releases/tag/3.4.0 .
