### ISSUE TITLE
Time format "yyyyMMdd.HHmmss.mmm" or "yyyyMMdd.HHmmss.SSS" ?

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb-zappbuild#404]
Hi,

Many zAppbuild scripts use the formatting string `yyyyMMdd.HHmmss.mmm` to format a date-time, but shouldn't the string `yyyyMMdd.HHmmss.SSS` be used instead?

`mmm` does not stand for "microsecond", unlike `SSS`, (`S` for fraction of second).

Confer [SimpleDateFormat patterns](https://groovy.apache.org/blog/groovy-dates-and-times-cheat#_simpledateformat_patterns).

**Comment by M-DLB** [comment]
Yes, I think you're right. I never noticed that before...
In some examples I've seen on our environment: 
`Build start at 20230911.043529.035`
The last part `035` is actually the minutes on 3 digits, as we see the same minutes in `043529`. I've check on other builds and it's always the same... 
We'll work on a fix for the next release! 

Thank for reporting that problem @FALLAI-Denis !
