### ISSUE TITLE
zUnit processing doesn't report files in the Build Report HTML report

### ISSUE THREAD

**Issue by M-DLB** [IBM/dbb-zappbuild#424]
Running zUnitConfig processing as part of the Build process doesn't produce a clean output of tests being executed:
![image](https://github.com/IBM/dbb-zappbuild/assets/47746258/d3555d6a-b346-496a-bc78-5bef5db5854c)

We can expect to have the files listed and other relevant information.

**Comment by dennis-behm** [comment]
@M-DLB 

The file attribute is implemented for JobExec API in DBB 2.0.1:
https://www.ibm.com/docs/api/v1/content/SS6T76_2.0.0/javadoc/com/ibm/dbb/build/JobExec.html#file-java.io.File-

I had opened the DBB idea - https://ideas.ibm.com/ideas/DBB-I-41 - to address the limitation in JCLExec. With the deprecation of the API, I doubt that this enhancement will be implemented.

To implement it, it would require to move to the new JobExec.

**Comment by M-DLB** [comment]
I guess we should investigate to move to JobExec then, since JCLExec is deprecated and will eventually disappear from a future release of DBB.

**Comment by dennis-behm** [comment]
Sorry, I think I messed something up with my response. The build file reference seems not to be implemented for the `JobExec` either.

I believe that the build file reference is a planned future item according to the status of the idea DBB-I-41 .

**Comment by dennis-behm** [comment]
This has been implemented with #561 and is part of zAppBuild since 3.10
