### ISSUE TITLE
Build status is set to 0 ("Clean") after exception thrown during Transfer.groovy

### ISSUE THREAD

**Issue by lauren-li** [IBM/dbb-zappbuild#445]
When a truncation error occurs during `Transfer.groovy` (e.g. a transferred text file is over 80 columns), an exception is thrown and the console output shows that the build ended in an `ERROR` state:

![Screenshot 2023-11-10 at 1 48 29 am](https://github.com/IBM/dbb-zappbuild/assets/45975633/dbb8ac0d-7106-4a0a-82a6-2ae6f1fc7aee)

However, the build result (i.e. retrieved with the `dbb build-result export` command) shows a status of `0 'CLEAN'`:

![Screenshot 2023-11-10 at 1 46 46 am](https://github.com/IBM/dbb-zappbuild/assets/45975633/24bc3a26-7c62-44f0-8754-1bfeecfd5ee2)

The truncation error exception results in the execution of the `catch` block in `Transfer.groovy`:
https://github.com/IBM/dbb-zappbuild/blob/main/languages/Transfer.groovy#L124-L129
![Screenshot 2023-11-10 at 1 56 18 am](https://github.com/IBM/dbb-zappbuild/assets/45975633/b264666d-6c9c-42b1-966c-d6ac9e2af4b1)

**Comment by M-DLB** [comment]
After investigation with @lauren-li and @monvora, it looks like an issue with the underlying technology that we will report to the development team.

**Comment by dennis-behm** [comment]
A defect has been identified with the FileMetadataStore, that will be addressed by the DBB development team.

**Comment by dennis-behm** [comment]
Please tack the defect in the file metadata store via the support channels.

Enhancements to improve the Exception handling has been delivered via [zAppBuild Release 3.6.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.6.0)

**Comment by dennis-behm** [comment]
[APAR PH58203](https://www.ibm.com/support/pages/apar/PH58203) has been opened to address the situation that CopyToPDS returns/reports a RC=0 on an exception
