### ISSUE TITLE
Missing exception handling in some of the groovy scripts

### ISSUE THREAD

**Issue by monvora** [IBM/dbb-zappbuild#446]
When an exception occurs during build run e.g. a truncation error in a file (there is some row that text exceeds the column limit), the build is terminate unexpectedly. We need a way to handle this exception and set the build status properly.

**Comment by dennis-behm** [comment]
This has been delivered via [zAppBuild Release 3.6.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.6.0)
