### ISSUE TITLE
Question : zUnit - While Running the test case - Failed to load the User program getting SOC4 Abend

### ISSUE THREAD

**Issue by APSDevp** [IBM/dbb-zappbuild#453]
Hi,

While Running the test case program the load module with the recorded program is not added to BUZINCL and that causes the abend SOC4. I assume this may be because some configuration is missing or with a property group.

Request your expertise to solve this issue. please help on it.

**Comment by dennis-behm** [comment]
@APSDevp - are you using the zUnitConfig.groovy that is generating the zunit test JCL?

It adds via these two entries the libraries into steplib.

https://github.com/IBM/dbb-zappbuild/blob/d177891a59a41b0947eacaf1e1e5a7ca199ac13a/languages/ZunitConfig.groovy#L59-L60

**Comment by APSDevp** [comment]
@dennis-behm 
Thanks for the response, Now I am trying with IDz Standalone and found that I have missed adding the Load module dataset in the Property group under zunit tab. After adding can see the load Dataset in the generated JCL however still getting the OC4 abend - showing as  **_"BZUP104S UNHANDLED ABEND=SOC4 DETECTED"_** 

Is this because of program level issue ? am trying very simple program which take single input via PARM and display it.

**Comment by dennis-behm** [comment]
If you run this by the **zUnit > Run Test case...** option that generates the JCL, you might need to override the STEPLIB

Blow snippet overwrites STEPLIB at the 6th position and adds the library with the application modules.
```
//STEPLIB  DD
//         DD
//         DD
//         DD
//         DD
//         DD  DISP=SHR,DSN=DBEHM.DBBRET.LOAD
```

Remember that the zAppBuild process is separating the into LOAD and TEST.LOAD libraries.

![image](https://github.com/IBM/dbb-zappbuild/assets/28918869/77d232aa-453c-4e02-8f7b-3b6312d38981)

**Comment by APSDevp** [comment]
@dennis-behm 

Thanks, I tried adding it - able to see loadlib getting override but still getting the same error - SOC4. I am looking into it might be because something got missed at the program level.

one doubt in IDz preference for playback dataset -I have given a HLQ for example DBHEM.DBB.PB  and here expectation is the recorded data will be stored in PDS DBHEM.DBB.PB.PGRNME , for me I am seeing dialogue box it coming as "PDS DBHEM.DBB.PB.PGRNME" but another qualifier - **_"AZUPLAY"_** getting added and it becomes not editable.

so recorded data is present in DBHEM.DBB.PB.AZUPLAY.PGRNME and JCL searching looking at DBHEM.DBB.PB.PGRNME which also leads to error.

Could you please let me know why it is creating a qualifier called "AZUPLAY" ? how to overcome this ?

**Comment by dennis-behm** [comment]
@APSDevp

It requires to understand the exact steps that you have performed, which version of IDZ you are using, and much more. In my scenario, I used 16.0.2.

This repository is for zAppBuild and its community of users, it is not the right place for zUnit usage questions.  Please go through the IBM support portal to get help specifically for IDZ/zUnit.

**Comment by APSDevp** [comment]
Thanks @dennis-behm
