### ISSUE TITLE
Config JAVA environment settings for ZOS connect V2 

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-zappbuild#467]
@M-DLB, 

I have found a defect in the zCEE2 script:
* The delimiter for the PATH should be `:` and not `;`
* Can we make this property optional? To me it feels this should rather be a capability to override the current use JAVA version ( `System.getProperty("java.home")`)

Could this be handled in the update of the script in #465 ?

https://github.com/IBM/dbb-zappbuild/blob/dd59b05112791ef1ea5fc710d821cb214b90142d/languages/zCEE2.groovy#L125-L130

**Comment by M-DLB** [comment]
Thanks @dennis-behm for spotting that.
It should now be fixed in #465

**Comment by dennis-behm** [comment]
Delivered via [zAppBuild 3.7.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.7.0)
