### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by mhardin18** [IBM/dbb-zappbuild#493]
https://github.com/IBM/dbb-zappbuild/blame/9f2561711cb4adae85376b8513d69b4220f4a9f0/utilities/GitUtilities.groovy#L81

If this is reached, it causes a missing property exception for both $dir and $gitBranchArr

		String warningMsg = "*! (GitUtils.getCurrentGitDetachedBranch) Warning obtaining branch name for ($dir). Multiple references point to the same commit. ($gitBranchArr)"

**Comment by dennis-behm** [comment]
Delivered via [zAppBuild 3.8.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.8.0)
