### ISSUE TITLE
Use filters and folder names in the languageConfigurationMapping.properties

### ISSUE THREAD

**Issue by wfezzani** [IBM/dbb-zappbuild#497]
Extend the `FilePropUtilities.groovy` script to handle the use of folder names and filters/wildcards in `languageConfigurationMapping.properties`.
This way, the user will be able to easier map a group of programs with a common language configuration property file, and avoid to enter all the program names and map each one with the corresponding property file.

- Example of the current `languageConfigurationMapping.properties` structure:
epscmort.cbl=languageConfigProps01
epscsmrd.cbl=languageConfigProps01
epsnbrvl.cbl=languageConfigProps01  
 
- Example of the desired `languageConfigurationMapping.properties` structure:
epscmort.cbl=languageConfigProps01
folder-name=languageConfigProps01
eps*.cbl=languageConfigProps01
$ps*.*= languageConfigProps01

Thanks you!

**Comment by dennis-behm** [comment]
Delivered via [zAppBuild 3.8.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.8.0)
