### ISSUE TITLE
easytrieve_outputDatasets wrongly named

### ISSUE THREAD

**Issue by erCrespo** [IBM/dbb-zappbuild#536]
https://github.com/IBM/dbb-zappbuild/blob/f3dfad68c6b727136830cd47c97a330b84fcc387/build-conf/Easytrieve.properties#L44

**Comment by dennis-behm** [comment]
Delivered with the [zAppBuild Release 3.10.0](https://github.com/IBM/dbb-zappbuild/releases/tag/3.10.0)
