### ISSUE TITLE
Investigations impactBuild of nested projects

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb-zappbuild#6]
Investigating into impactBuild of nested projects:
While MortgageApplication sample is now shipped as a subfolder in zAppBuild, I see a that in an impactBuild scenario, the relative path to the file is not correctly resolved:

https://github.com/IBM/dbb-zappbuild/blob/421c805b4f150bb6f3d2a750b6e599447935e7a0/utilities/ImpactUtilities.groovy#L314

Impact Utilities returns the wrong filePath:
```
** Storing MortgageApplication : e3a10c29a59c8bf5f1b68d07d031d0701491b741
** Calculating changed files for directory /var/dbb/buildhome/workspace/Mortgage-Sample-Nested-Project/Mortgage-ImpactBuild-NestedPrj/samples/MortgageApplication
** Diffing baseline e3a10c29a59c8bf5f1b68d07d031d0701491b741 -> current 9b7953582a63f1f6db63f7ac06d5a957eb5c4cf7
*** Changed files for directory /var/dbb/buildhome/workspace/Mortgage-Sample-Nested-Project/Mortgage-ImpactBuild-NestedPrj/samples/MortgageApplication:
@@ fixFilePath (workspace+fixedFileName)/var/dbb/buildhome/workspace/Mortgage-Sample-Nested-Project/Mortgage-ImpactBuild-NestedPrj/samples/MortgageApplication/epsmpmt.cbl
```

**Comment by drbruce-git** [comment]
@dennis-behm What are the values of properties.workspace and properties.application?

**Comment by dennis-behm** [comment]
Hi Dan, here is the output including properties.workspace and application:

```
@@ fixFilePath (workspace+fixedFileName) : /var/dbb/buildhome/workspace/Mortgage-Sample-Nested-Project/Mortgage-ImpactBuild-NestedPrj/samples/MortgageApplication/epsmpmt.cbl
@@ fixFilePath (workspace) : /var/dbb/buildhome/workspace/Mortgage-Sample-Nested-Project/Mortgage-ImpactBuild-NestedPrj/samples
@@ fixFilePath (application) : MortgageApplication
```

**Comment by nlopez1-ibm** [comment]
Hi Guys, Ran into the same issues.   The fixFilePath  drops the subfolder in my case.
See how  the Input file (from a git diff) has /cobol but missing in fixedFilename which then fails file.exists and not added to buildList

`//TESTRES  fixFilePath  Input file = Mortgage-SA-DAT/cobol/datmlist.cbl    dir=/u/nlopez/DAT-Demo-Workspace/Mortgage-SA-DAT    fixedFileName=Mortgage-SA-DAT/datmlist.cbl   indexOf slash =  15
`

**Comment by nlopez1-ibm** [comment]
WorkAround:  testing with Brice and my own test case, just add my line after the def. 
```
def fixFilePath(String file, String dir, boolean mustExist ) {
def fixedFileName = buildUtils.relativizePath(dir) + ( file.indexOf ("/") >= 0 ? file.substring(file.lastIndexOf("/")) : file )
			
//NJL - Patch
fixedFileName = file 
			
```

**Comment by dennis-behm** [comment]
The challenge with this part is that we see different usages with the git repositories. 

You can use the **git repository name as the application name** for zAppBuild (used in --application). 

`build.groovy --sourceDir /u/ibmuser/build/ --workDir /u/ibmuser/build/work --hlq IBMUSER.ACME --application MortgageApplication --verbose --impactBuild`

But could also use **applications within the repository**, like in the samples of zAppBuild:

`build.groovy --sourceDir /u/ibmuser/build/dbb-zappbuild/samples --workDir /u/ibmuser/build/work --hlq DBEHM.ACME --application MortgageApplication --verbose --impactBuild`

You can even think of a nested repositories, when you build across several repos.

**Comment by dennis-behm** [comment]
We have introduced support for additional scenarios of nested projects via #10 and #24 . Please open a new issue, if you are facing new problems with the filePath during the resolution of the physical file for the build list of impacted programs.
