### ISSUE TITLE
Add support for external SYSLIB property (in Build Report)

### ISSUE THREAD

**Issue by nixpix49** [IBM/dbb-zappbuild#77]
What do we need that for ? 
The BuildReport can then be used as input to the functionality described here: https://github.com/IBM/dbb/tree/master/Pipeline/RunIDZCodeReview.
If the external SYSLIBs isn't present (copybooks) in the BuildReport, we can't use the BuildReport as input.

Thanks

**Comment by dennis-behm** [comment]
Morning @nixpix49 ,

With the DBB API, it is possible to report all the DDAllocations in the build report by using this API: https://www.ibm.com/support/knowledgecenter/en/SS6T76_1.1.0/javadoc/com/ibm/dbb/build/DDStatement.html#report-boolean-

It looks like this:
```
compile.dd(new DDStatement().dsn(syslibDataset).options("shr").report(true))
```
along the processing of the _SYSLIB_ https://github.com/IBM/dbb-zappbuild/blob/development/languages/Cobol.groovy#L210

You are able to have all the datasets in the SYSLIB, see a sample :
![image](https://user-images.githubusercontent.com/28918869/110755866-bc66a880-8249-11eb-97ac-617c7d3c3c0f.png)

However, while not all the users of zAppBuild also make use of the IDZCodeReview, and I don't would like to overload the BuildReport.

Therefore, I will open an enhancement on the ibm/dbb to have a property, where we can add an external syslib as well. I know that this leads to a duplication of the SYSLIB info, however I don't see any other way to solve it right now.

Thoughts?

**Comment by dajsen** [comment]
Thanx Dennis! Will check it out!
Have a nice weekend and stay SAFE!

**Comment by dennis-behm** [comment]
@dajsen please check this out. It is delivered in https://github.com/IBM/dbb/pull/72 and please close this issue if this is sufficient for you. Thx. Stay Safe as well!
