### ISSUE TITLE
ImpactBuild should be triggered for Properties Changes

### ISSUE THREAD

**Issue by bala-azha** [IBM/dbb-zappbuild#86]
Changes in the properties files should pick the corresponding source code during impact build (even when corresponding source is not changed) . For example when we change the cobol_compileParms in the properties file, it will not pick all the source code affected during impact build as only source file changes are considered during impact build but in reality changing the compileParms actually changes the load module created. even though there is no change in the source module. This is also applicable for changes in file specific properties (like cobol_testcase = true :: **/testcase/*.cbl) also.

**Comment by dennis-behm** [comment]
@bala-azha Thanks for bringing this up to our attention. This sounds like a very interesting enhancement, which was also raised by other users.

It took us a while to think how we could support this in zAppBuild. With the LogicalFiles with its LogicalDependencies , which are captured within the collection, we have a lot of flexibility. We would be actually be able to add _any_ other logical dependency to an logical file. Our current thinking is to add logicalDependencies for Build Property (with it's own dependency category) based on list of properties, which should be considered in an impactBuild scenario.

Currently, we think about the Compiler Version, Compile Options and Link Options. Do you see any other build properties, which you would like to include?

**Comment by dennis-behm** [comment]
@bala-azha @drbruce-git 

I developed a prototype for this enhancement. When scanning the files, it adds LogicalDependencies for the build properties to the LogicalFile: https://github.com/dennis-behm/dbb-zappbuild/blob/properties/utilities/ImpactUtilities.groovy#L354-L366

It detects the change of the property file and passes control to a new gitUtil method to understand the actual change. I pass it to a Java Properties object for validation before returning all the modified build properties to the impact calculation.

After the impact analysis phase, there is a new calculation of impacted files for the list of changed properties: 

![image](https://user-images.githubusercontent.com/28918869/116743962-f6f2f300-a9f9-11eb-8b40-5aabe3592150.png)

You can browse my fork at https://github.com/dennis-behm/dbb-zappbuild/tree/properties

I need to do some housekeeping, while I used the new test framework, which I modified to my needs.

**Comment by dennis-behm** [comment]
While this is delivered, I am closing the issue.
